server.port: 4084
spring.jpa.generate-ddl: true
spring.jpa.properties.hibernate.dialect: com.hedvig.memberservice.PostgresDialect
spring.jpa.properties.javax.persistence.schema-generation.create-source: metadata
spring.jpa.properties.javax.persistence.schema-generation.scripts.action: create
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target: create.sql
spring.jpa.hibernate.ddl-auto: update
spring.jackson.serialization.write_dates_as_timestamps: false

management.security.enabled: false


logging.level.com.hedvig: DEBUG


